### PR TITLE
Create C.Dijkstra? Solutions [ Hacktoberfest ]

### PR DESCRIPTION
**Pull request by Aphrodicez**

### CODE REVIEW

**Comment by Hawk1810** [comment]
This Problem is already present in repo

**Comment by Aphrodicez** [comment]
> This Problem is already present in repo

Excuse me sir, but I couldn't find it anywhere.

**Comment by Hawk1810** [comment]
https://github.com/Hawk1810/Competitive_Coding-Essentials/tree/main/codeforces/Cakeminator

**Comment by Hawk1810** [comment]
okayy Nice!

**Comment by Aphrodicez** [comment]
Sincerely apologize sir, I forgot to change the link 😢

**Pull request merged**
